language: java
sudo: required
dist: xenial
jdk:
  - openjdk14

cache:
  directories:
    - $HOME/.m2/repository

script:
  - ./mvnw test jacoco:report coveralls:report
#  - ./mvnw test -e

#after_success:
#  - ./mvnw clean test jacoco:report coveralls:report