version: '3.8'

networks:
  backend:
    driver: bridge

services:

  postgres:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5430:5432"
    volumes:
      - /datastore/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: tododb
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      backend:
        aliases:
          - "postgres"
    restart: on-failure

  todoapp:
    image: rsh12/todo:0.0.1-SNAPSHOT
    ports:
      - "8080"
    #     - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tododb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
      TOKEN: ${TOKEN}
    networks:
      backend:
        aliases:
          - "todoapp"
    depends_on:
      - postgres
      - rabbit
    restart: on-failure

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      backend:
        aliases:
          - "rabbitmq"

    # todo: add password-reset service

  prometheus:
    image: prom/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: todo-prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      backend:
        aliases:
          - "prometheus"
    depends_on:
      - todoapp
    restart: on-failure

  grafana:
    image: grafana/grafana
    container_name: todo-grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/:/etc/grafana/
    ports:
      - "3000:3000"
    networks:
      backend:
        aliases:
          - "grafana"
    restart: on-failure

  web:
    image: nginx
    container_name: nginx
    networks:
      backend:
        aliases:
          - "nginx"
    ports:
      - "8000:80" # because the 80th port on the local machine is already in use
    #     - 443:443 # ssl off by default
    depends_on:
      - todoapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl # ssl off by default
    restart: always
